kind: pipeline
name: default
steps:
- name: docker
  image: plugins/docker
  settings:
    registry: 192.168.10.200:5000
    repo: "192.168.10.200:5000/${DRONE_REPO_NAME}"
    tags: latest
    insecure: true

- name: kubectl
  image: 192.168.10.200:5000/drone-kubectl
  pull: always
  settings:
    server:
      from_secret: kubernetes_server
    cert:
      from_secret: kubernetes_cert
    token:
      from_secret: kubernetes_token
    kubectl: 
      - "get pods"
      - "get ns"

---
kind: secret
name: kubernetes_server
get:
  path: drone-kubernetes
  name: server
---
kind: secret
name: kubernetes_cert
get:
  path: drone-kubernetes
  name: cert
---
kind: secret
name: kubernetes_token
get:
  path: drone-kubernetes
  name: token
